name: Deploy to AlmaLinux

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Verify JAR file
        run: |
          ls -lh target/pos-*.jar
          file target/pos-*.jar

      - name: Clean remote directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo rm -rf /opt/pos/pos.jar /opt/pos/pos-*.jar
            mkdir -p /opt/pos

      - name: Deploy JAR to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/pos-*.jar"
          target: "/opt/pos/"
          strip_components: 1

      - name: Rename JAR file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mv /opt/pos/pos-*.jar /opt/pos/pos.jar
            sudo chown deployer:deployer /opt/pos/pos.jar
            sudo chmod 500 /opt/pos/pos.jar

      - name: Restart POS Service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo -S systemctl daemon-reload
            sudo -S systemctl restart pos.service