name: Deploy to AlmaLinux

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Verify JAR file
        run: |
          ls -lh target/pos-*.jar
          file target/pos-*.jar

      - name: Prepare server directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          env:
            SUDO_PWD: ${{ secrets.SUDO_PASSWORD }}
          script: |
            echo "$SUDO_PWD" | sudo -S rm -rf /opt/pos/pos.jar
            echo "$SUDO_PWD" | sudo -S mkdir -p /opt/pos
            echo "$SUDO_PWD" | sudo -S chown deployer:deployer /opt/pos

      - name: Upload JAR file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/pos-*.jar"
          target: "/opt/pos/"
          strip_components: 1

      - name: Configure application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          env:
            SUDO_PWD: ${{ secrets.SUDO_PASSWORD }}
          script: |
            echo "$SUDO_PWD" | sudo -S mv /opt/pos/pos-*.jar /opt/pos/pos.jar
            echo "$SUDO_PWD" | sudo -S chown deployer:deployer /opt/pos/pos.jar
            echo "$SUDO_PWD" | sudo -S chmod 500 /opt/pos/pos.jar
            ls -la /opt/pos/

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          env:
            SUDO_PWD: ${{ secrets.SUDO_PASSWORD }}
          script: |
            echo "$SUDO_PWD" | sudo -S systemctl daemon-reload
            echo "$SUDO_PWD" | sudo -S systemctl restart pos.service
            sleep 5
            echo "$SUDO_PWD" | sudo -S systemctl status pos.service